basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/mongodb/MongoDBSubmodelAPI.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/java/org/eclipse/basyx/regression/AASServer/TestMongoDBServer.java

Adds test for delegate invokations to TestMongoDBServer
Signed-off-by: Maximilian Conradi <maximilian.conradi@iese.fraunhofer.de>

Refactors MongoDBSubmodelAPI to support delegating operation invokes

---

.github/workflows/maven-run-tests.yml

Dear Frank,
This pull request adds Basyx.tck project in the CI pipeline.
Thanks and Regards
Mohammad Ghazanfar Ali Danish

Adds Basyx.tck project in the CI pipeline

---

basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/AASServerComponent.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/mongodb/MongoDBAASAggregator.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/java/org/eclipse/basyx/regression/AASServer/AASServerSuite.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/java/org/eclipse/basyx/regression/AASServer/MqttAASServerSuite.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/java/org/eclipse/basyx/regression/AASServer/TestAASServerWithInMemoryMqtt.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/java/org/eclipse/basyx/regression/AASServer/TestAASServerWithMongoDbAndMqtt.java

* Reworks ServerComponent for mqtt support in submodel
* Adds to MQTT Submodel functionality to InMemory backend
* Adds to MQTT Submodel functionality to MongoDB backend
* Adds feature to AASServer to automatically add MQTT events to submodels and shells
* Adds corresponding tests

Adds MQTT functionality SubmodelAggregator

---

basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/AASServerComponent.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/configuration/BaSyxAASServerConfiguration.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/resources/aas.properties

* Needs https://github.com/eclipse-basyx/basyx-java-sdk/pull/40
Co-authored-by: Rene-Pascal Fischer <rene-pascal.fischer@iese.fraunhofer.de>
Co-authored-by: Jannik Fried <jannik.fried@iese.fraunhofer.de>
Signed-off-by: Jannis Jung <jannis.jung@iese.fraunhofer.de>

Adds AASAggregator authorization AASServerComponent

---

basyx.components/basyx.components.docker/basyx.components.AASServer/Dockerfile
basyx.components/basyx.components.docker/basyx.components.AASServer/wait-for-it-env.sh
basyx.components/basyx.components.docker/basyx.components.AASServer/wait-for-it.sh

Co-authored-by: Zai Müller-Zhang <zai.mueller-zhang@iese.fraunhofer.de>
Signed-off-by: Daniel Espen <Daniel.Espen@iese.fraunhofer.de>

Add wait-for-it to Dockerfile for AASServer

---

basyx.components/.gitignore
basyx.components/basyx.components.docker/basyx.components.registry/src/main/java/org/eclipse/basyx/components/registry/RegistryComponent.java
basyx.components/basyx.components.docker/basyx.components.registry/src/main/java/org/eclipse/basyx/components/registry/configuration/BaSyxRegistryConfiguration.java
basyx.components/basyx.components.docker/basyx.components.registry/src/main/java/org/eclipse/basyx/components/registry/servlet/TaggedDirectoryServlet.java
basyx.components/basyx.components.docker/basyx.components.registry/src/main/resources/registry.properties
basyx.components/basyx.components.docker/basyx.components.registry/src/test/java/org/eclipse/basyx/regression/registry/TestTaggedDirectoryComponent.java
basyx.components/basyx.components.docker/basyx.components.registry/src/test/java/org/eclipse/basyx/regression/registry/TestTaggedDirectoryRaw.java

Rules:
This version only supports tagged directory with inMemory backed.
* SQL
* MongoDB
* MQQT Eventing
* Authorization
currently are not supported yet.

Adds TaggedDirectory functionality to OTC RegistryComponent

---

basyx.components/basyx.components.docker/basyx.components.AASServer/pom.xml
basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/AASServerComponent.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/executable/AASServerExecutable.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/mongodb/MongoDBAASAggregator.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/java/org/eclipse/basyx/regression/AASServer/TestMongoDBAggregator.java
basyx.components/basyx.components.docker/basyx.components.registry/pom.xml
basyx.components/basyx.components.docker/pom.xml
basyx.components/basyx.components.lib/pom.xml
basyx.components/pom.xml

Merges branch 'release/1.0.2' into development

---

.github/workflows/maven-run-tests.yml

Dear Frank,
This PR adds CI to build basyx sdk.
Thanks and Regards
Mohammad

Adds CI to build basyx sdk

---

basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/AASServerComponent.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/aascomponent/AASComponentAggregatorFactory.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/aascomponent/IAASServerDecorator.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/aascomponent/IAASServerFeature.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/authorization/AuthorizedAASServerDecorator.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/authorization/AuthorizedAASServerFeature.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/executable/AASServerExecutable.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/mongodb/MongoDBAASAggregator.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/mqtt/MqttAASServerDecorator.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/mqtt/MqttAASServerFeature.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/java/org/eclipse/basyx/regression/AASServer/MqttAASServerSuite.java

* Adds AASServerFeature Interface
* Adds AASServerDecorator Interface
* Adds Mqtt and Authorization Feature
* Fixes JavaDoc
* Removes MQTT Support for MongoDB  -> will be added again in a later commit
Co-authored-by: Rene-Pascal Fischer <rene-pascal.fischer@iese.fraunhofer.de>
Co-authored-by: Jannis Jung <jannis.jung@iese.fraunhofer.de>
Signed-off-by: Jannik Fried <jannik.fried@iese.fraunhofer.de>

Reworks AASServerComponent to enable DecoratingFactories as Features

---

basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/AASServerComponent.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/configuration/BaSyxAASServerConfiguration.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/java/org/eclipse/basyx/regression/AASServer/AASServerComponentTest.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/java/org/eclipse/basyx/regression/AASServer/configuration/TestBaSyxAASServerConfigurationPropertyFileParsing.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/resources/aas_multiple_different_source.properties
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/resources/aas_single_json_source.properties
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/resources/aas_single_source.properties
basyx.components/pom.xml

Dear Frank,
This PR adds new implementation to support loading of multiple serialized AASs (#28 ).

Adds new implementation to support loading of multiple AAS

---

basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/mongodb/MongoDBAASAggregator.java

Description:
- Replaces getAASApi with create

Replaces usage of old methods with create method

---

basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/executable/AASServerExecutable.java

Fixes potential issue created with https://github.com/eclipse-basyx/basyx-java-components/pull/59

Removes code duplicate from executable to avoid adding features twice

---

basyx.components/basyx.components.docker/basyx.components.AASServer/wait-for-it-env.sh

Signed-off-by: Zai Zhang <zai.mueller-zhang@iese.fraunhofer.de>

Change the environemnt variable waiting_for to lower case style

---

basyx.components/basyx.components.updater/basyx.components.updater.examples/basyx.components.updater.examples.activemq-jsonata-aas/src/main/resources/jsonatatransformer.json
basyx.components/basyx.components.updater/basyx.components.updater.examples/basyx.components.updater.examples.hono-jsonata-aas/src/main/resources/jsonatatransformer.json
basyx.components/basyx.components.updater/basyx.components.updater.examples/basyx.components.updater.examples.http-jsonata-delegator/src/main/resources/jsonatatransformer.json
basyx.components/basyx.components.updater/basyx.components.updater.examples/basyx.components.updater.examples.kafka-jsonata-aas/src/main/resources/jsonatatransformer.json
basyx.components/basyx.components.updater/basyx.components.updater.examples/basyx.components.updater.examples.kafka-jsonatamultiple-aas/src/main/resources/jsonatatransformer.json
basyx.components/basyx.components.updater/basyx.components.updater.examples/basyx.components.updater.examples.mqtt-jsonata-aas/src/main/resources/jsonatatransformer.json

Replace hardcoded paths in jsonatatransformer.json of all Updater examples with simple relative paths.
Closes #71

fix jsonata paths in Updater examples

---

basyx.components/basyx.components.updater/basyx.components.updater.camel-aas/src/main/java/basyx/components/updater/aas/AASProducer.java

solves #80 
adapts the `AASProducer` process method to infer the correct `valueType` from the `connectedProperty`
**Important:** this requires the valueType to be properly set in the AAS on the Server, e.g. through a loaded AASX. An incompatible valueType throws as an examle `java.lang.NumberFormatException`

adapt AASProducer process method to infer correct valueType 

---

basyx.components/basyx.components.updater/basyx.components.updater.camel-aas/pom.xml
basyx.components/basyx.components.updater/basyx.components.updater.core/pom.xml
basyx.components/basyx.components.updater/basyx.components.updater.examples/basyx.components.updater.examples.aasinternal/pom.xml
basyx.components/basyx.components.updater/basyx.components.updater.examples/basyx.components.updater.examples.aasserver/pom.xml
basyx.components/basyx.components.updater/basyx.components.updater.examples/basyx.components.updater.examples.activemq-jsonata-aas/pom.xml
basyx.components/basyx.components.updater/basyx.components.updater.examples/basyx.components.updater.examples.hono-jsonata-aas/pom.xml
basyx.components/basyx.components.updater/basyx.components.updater.examples/basyx.components.updater.examples.httppolling-jsonata-aas/pom.xml
basyx.components/basyx.components.updater/basyx.components.updater.examples/basyx.components.updater.examples.kafka-jsonata-aas/pom.xml
basyx.components/basyx.components.updater/basyx.components.updater.examples/basyx.components.updater.examples.kafka-jsonatamultiple-aas/pom.xml
basyx.components/basyx.components.updater/basyx.components.updater.examples/basyx.components.updater.examples.mqtt-jsonata-aas/pom.xml
basyx.components/basyx.components.updater/basyx.components.updater.examples/basyx.components.updater.examples.opcua-jsonata-aas/pom.xml
basyx.components/basyx.components.updater/basyx.components.updater.examples/basyx.components.updater.examples.prometheus-jsonata-aas/pom.xml

Updates BaSyx dependencies to latest release

---

basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/aascomponent/MongoDBAASServerComponentFactory.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/mongodb/MongoDBSubmodelAPI.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/mongodb/MongoDBSubmodelAggregator.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/mongodb/MongoDBSubmodelAggregatorFactory.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/java/org/eclipse/basyx/regression/AASServer/mongodb/TestMongoDBAggregator.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/java/org/eclipse/basyx/regression/AASServer/mongodb/TestMongoDBServer.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/java/org/eclipse/basyx/regression/AASServer/mongodb/TestMongoDBSubmodelAggregator.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/java/org/eclipse/basyx/regression/AASServer/mongodb/TestMongoDBSubmodelProvider.java

Introduces MongoDBSubmodelAggregator

---

basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/resources/aas.properties
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/resources/aas_multiple_different_source.properties
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/resources/aas_single_json_source.properties
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/resources/aas_single_source.properties

Changes registry.hostpath to the correct registry.host in .properties files
Signed-off-by: Maximilian Conradi <maximilian.conradi@iese.fraunhofer.de>

Fixes registry.hostpath in .properties files

---

basyx.components/basyx.components.docker/basyx.components.AASServer/Dockerfile
basyx.components/basyx.components.docker/basyx.components.registry/Dockerfile

Fixes wrong base image for docker

---

basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/java/org/eclipse/basyx/regression/AASServer/AASXSuite.java
basyx.components/basyx.components.docker/basyx.components.registry/src/test/java/org/eclipse/basyx/regression/registry/ITRegistryRaw.java
basyx.components/basyx.components.lib/src/main/java/org/eclipse/basyx/tools/webserviceclient/WebServiceRawClient.java

Reverts eclipse-basyx/basyx-java-components#130

Revert "javax replaced with jakarta"

---

.github/dependabot.yml

Integrates dependabot for Github Actions and Maven

---

basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/AASServerComponent.java

Fixes getURL returning wrong url in some cases

---

basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/AASServerComponent.java

Fixes order of Feature initialization

---

basyx.components/basyx.components.docker/basyx.components.AASServer/pom.xml
basyx.components/basyx.components.docker/basyx.components.registry/pom.xml
basyx.components/basyx.components.lib/pom.xml
basyx.components/pom.xml

Fixes logging

---

basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/configuration/BaSyxAASServerConfiguration.java
basyx.components/basyx.components.docker/basyx.components.registry/src/main/java/org/eclipse/basyx/components/registry/configuration/BaSyxRegistryConfiguration.java

Modification of reg-id and repo-id via env variables wasn't possible

MQTTV2 reg-id / repo-id modification via env variables

---

basyx.components/basyx.components.docker/basyx.components.registry/src/main/java/org/eclipse/basyx/components/registry/mongodb/MongoDBTaggedDirectory.java
basyx.components/basyx.components.docker/basyx.components.registry/src/test/java/org/eclipse/basyx/regression/registry/TestMongoDBTaggedDirectory.java

Signed-off-by: Jannis Jung <jannis.jung@iese.fraunhofer.de>

Fixes Bug: MongoDBTaggedDirectory does not load tags

---

basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/authorization/internal/AuthorizedDefaultServlet.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/authorization/internal/IAuthorizersProvider.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/authorization/internal/PathTargetInformation.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/mongodb/MongoDBAASAggregator.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/java/org/eclipse/basyx/regression/AASServer/mongodb/TestMongoDBServer.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/java/org/eclipse/basyx/regression/AASServer/mongodb/TestMongoDBSubmodelProvider.java
basyx.components/basyx.components.docker/basyx.components.registry/src/main/java/org/eclipse/basyx/components/registry/authorization/internal/IAuthorizersProvider.java
basyx.components/basyx.components.lib/src/main/java/org/eclipse/basyx/components/configuration/CFGBaSyxConnection.java
basyx.components/basyx.components.lib/src/main/java/org/eclipse/basyx/components/security/authorization/internal/AuthorizationDynamicClassLoader.java
basyx.components/basyx.components.lib/src/main/java/org/eclipse/basyx/models/controlcomponent/ControlComponent.java
basyx.components/basyx.components.lib/src/test/java/org/eclipse/basyx/regression/sql/SQLQueriesTest.java
basyx.components/basyx.components.lib/src/test/java/org/eclipse/basyx/regression/support/processengine/stubs/BPMNEngineStub.java

Removes warnings

---

basyx.components/basyx.components.docker/basyx.components.AASServer/Dockerfile
basyx.components/basyx.components.docker/basyx.components.registry/Dockerfile

Adds Wget installation to components' Dockerfiles

---

basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/mongodb/MongoDBSubmodelAPI.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/java/org/eclipse/basyx/regression/AASServer/mongodb/TestMongoDBServer.java

Fixes delegated operation handling in MongoDBSubmodelAPI

---

basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/mongodb/MongoDBAASAPI.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/mongodb/MongoDBSubmodelAPI.java

Next try with a smaller change

Removing _id from aas/sm where not already removed

---

basyx.aasrepository-http/src/test/java/org/eclipse/digitaltwin/basyx/aasrepository/http/TestAasRepositoryHTTP.java
basyx.http/pom.xml
basyx.http/src/main/java/org/eclipse/digitaltwin/basyx/http/serialization/Aas4JReferableListWrapper.java
basyx.http/src/test/java/org/eclipse/digitaltwin/basyx/http/serialization/TestReferableListJsonSerializer.java

Fixes bug related to AAS4J handling of List<Referable>

---

basyx.submodelrepository-backend-inmemory/src/main/java/org/eclipse/digitaltwin/basyx/submodelrepository/InMemorySubmodelRepository.java
basyx.submodelrepository-core/src/main/java/org/eclipse/digitaltwin/basyx/submodelrepository/SubmodelRepository.java
basyx.submodelrepository-core/src/test/java/org/eclipse/digitaltwin/basyx/submodelrepository/core/SubmodelRepositorySuite.java
basyx.submodelrepository-http/src/main/java/org/eclipse/digitaltwin/basyx/submodelrepository/http/SubmodelRepositoryApiHTTPController.java
basyx.submodelrepository-http/src/main/java/org/eclipse/digitaltwin/basyx/submodelrepository/http/SubmodelRepositoryHTTPApi.java
basyx.submodelrepository-http/src/test/java/org/eclipse/digitaltwin/basyx/submodelrepository/http/TestSubmodelRepositoryHTTP.java
basyx.submodelrepository-http/src/test/resources/SubmodelElement.json
basyx.submodelservice-backend-inmemory/src/main/java/org/eclipse/digitaltwin/basyx/submodelservice/InMemorySubmodelService.java
basyx.submodelservice-core/src/main/java/org/eclipse/digitaltwin/basyx/submodelservice/SubmodelService.java
basyx.submodelservice-core/src/test/java/org/eclipse/digitaltwin/basyx/submodelservice/SubmodelServiceSuite.java

Signed-off-by: Vasil Tenev <vasil.tenev@iese.fraunhofer.de>

feat: Submodel Repository - Specific SubmodelElement retrieval

---

basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/mongodb/MongoDBSubmodelAPI.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/java/org/eclipse/basyx/regression/AASServer/mongodb/TestMongoDBSubmodelAPI.java

Fixes MongoDBSubmodelAPI value retrieval bug

---

basyx.submodelrepository-backend-inmemory/src/main/java/org/eclipse/digitaltwin/basyx/submodelrepository/InMemorySubmodelRepository.java
basyx.submodelrepository-core/src/main/java/org/eclipse/digitaltwin/basyx/submodelrepository/SubmodelRepository.java
basyx.submodelrepository-core/src/test/java/org/eclipse/digitaltwin/basyx/submodelrepository/core/SubmodelRepositorySuite.java
basyx.submodelrepository-http/src/main/java/org/eclipse/digitaltwin/basyx/submodelrepository/http/SubmodelRepositoryApiHTTPController.java
basyx.submodelrepository-http/src/main/java/org/eclipse/digitaltwin/basyx/submodelrepository/http/SubmodelRepositoryHTTPApi.java
basyx.submodelrepository-http/src/test/java/org/eclipse/digitaltwin/basyx/submodelrepository/http/SubmodelRepositoryHTTPTestUtils.java
basyx.submodelrepository-http/src/test/java/org/eclipse/digitaltwin/basyx/submodelrepository/http/TestSubmodelRepositorySubmodelElementsHTTP.java
basyx.submodelrepository-http/src/test/java/org/eclipse/digitaltwin/basyx/submodelrepository/http/TestSubmodelRepositorySubmodelHTTP.java
basyx.submodelservice-backend-inmemory/src/main/java/org/eclipse/digitaltwin/basyx/submodelservice/InMemorySubmodelService.java
basyx.submodelservice-core/src/main/java/org/eclipse/digitaltwin/basyx/submodelservice/SubmodelService.java
basyx.submodelservice-core/src/test/java/org/eclipse/digitaltwin/basyx/submodelservice/SubmodelServiceSuite.java

Co-authored-by: Jannik Oliver Fried <Jannik.Fried@iese.fraunhofer.de>

Implements set/getSubmodelElementValue for Properties

---

basyx.aasenvironment.component/pom.xml
basyx.aasrepository-backend-inmemory/pom.xml
basyx.aasrepository-core/pom.xml
basyx.aasrepository-feature-aasxupload/pom.xml
basyx.aasrepository-feature-consoleprinter/pom.xml
basyx.aasrepository-feature-mqtt/pom.xml
basyx.aasrepository-http/pom.xml
basyx.aasrepository.component/pom.xml
basyx.aasservice-backend-inmemory/pom.xml
basyx.aasservice-core/pom.xml
basyx.aasservice-feature-consoleprinter/pom.xml
basyx.core/pom.xml
basyx.http/pom.xml
basyx.submodelrepository-backend-inmemory/pom.xml
basyx.submodelrepository-core/pom.xml
basyx.submodelrepository-http/pom.xml
basyx.submodelrepository.component/pom.xml
basyx.submodelservice-backend-inmemory/pom.xml
basyx.submodelservice-core/pom.xml

Updates version to 2.0.0-SNAPSHOT

---

.gitignore
basyx.aasrepository-feature-mqtt/pom.xml
basyx.aasrepository-feature-mqtt/src/main/java/org/eclipse/digitaltwin/basyx/aasrepository/feature/mqtt/MqttAasRepository.java
basyx.aasrepository-feature-mqtt/src/main/java/org/eclipse/digitaltwin/basyx/aasrepository/feature/mqtt/MqttAasRepositoryFactory.java
basyx.aasrepository-feature-mqtt/src/main/java/org/eclipse/digitaltwin/basyx/aasrepository/feature/mqtt/MqttAasRepositoryFeature.java
basyx.aasrepository-feature-mqtt/src/main/java/org/eclipse/digitaltwin/basyx/aasrepository/feature/mqtt/MqttAasRepositoryTopicFactory.java
basyx.aasrepository-feature-mqtt/src/test/java/org/eclipse/digitaltwin/basyx/aasrepository/feature/mqtt/MqttTestListener.java
basyx.aasrepository-feature-mqtt/src/test/java/org/eclipse/digitaltwin/basyx/aasrepository/feature/mqtt/TestMqttV2AASAggregatorObserver.java
basyx.aasrepository-feature-mqtt/src/test/resources/config/moquette.conf

Adds missing tests for Repository MQTT Eventing

---

basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/java/org/eclipse/basyx/regression/AASServer/MqttAASServerSuite.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/java/org/eclipse/basyx/regression/AASServer/MqttV2AASServerSuite.java

Waits for Message propagation in tests

---

basyx.components/basyx.components.lib/src/main/java/org/eclipse/basyx/components/security/authorization/internal/AuthorizationDynamicClassLoader.java

Signed-off-by: wege <florian.wege@iese.fraunhofer.de>

Fix exception message AuthorizationDynamicClassLoader

---

basyx.aasenvironment.component/pom.xml
basyx.aasenvironment.component/src/main/resources/application.properties
basyx.aasrepository.component/pom.xml
basyx.aasrepository.component/src/main/resources/application.properties
basyx.submodelrepository.component/pom.xml
basyx.submodelrepository.component/src/main/resources/application.properties

Signed-off-by: Jannik Fried <Jannik.Fried@iese.fraunhofer.de>

Adds Spring Boot Actuator to enable Health Endpoint

---

.github/workflows/maven_run_test.yml
docker-compose.yml

Fixes https://github.com/admin-shell-io/aas-cloud-repository-java/issues/31

Moved dev environment from github action to docker compose

---

basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/mongodb/MongoDBSubmodelAPI.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/resources/mongodb.properties
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/java/org/eclipse/basyx/regression/AASServer/mongodb/TestMongoDBSubmodelAPI.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/resources/testfile.xml
basyx.components/basyx.components.lib/src/main/java/org/eclipse/basyx/components/configuration/BaSyxMongoDBConfiguration.java

Depends on https://github.com/eclipse-basyx/basyx-java-sdk/pull/239

Adds File Handling for MongoDB Backend

---

basyx.tck/basyx.tck.AASServer/pom.xml
basyx.tck/basyx.tck.AASServer/src/test/java/org/eclipse/basyx/testsuite/regression/aas/metamodel/AASAggregatorSuiteWithDefinedURL.java
basyx.tck/basyx.tck.registry/pom.xml
basyx.tck/pom.xml

Fixes TCK fails with own components

---

basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/AASServerComponent.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/java/org/eclipse/basyx/regression/AASServer/AASXSuite.java

Addresses the issue (https://github.com/eclipse-basyx/basyx-java-components/issues/329)

Fixes files not served issue

---

basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/mongodb/MongoDBAASAggregator.java
basyx.components/basyx.components.docker/basyx.components.AASServer/src/test/java/org/eclipse/basyx/regression/AASServer/mongodb/TestMongoDBAAASAPI.java
basyx.components/basyx.components.lib/src/main/java/org/eclipse/basyx/components/internal/mongodb/MongoDBBaSyxStorageAPI.java

* Does not work with CosmosDB at the moment

Removes indexing
